//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Personel_Finansal_Takip.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class fazla_mesai
    {
        public int Id { get; set; }
        public Nullable<int> personel_id { get; set; }
        public Nullable<int> sure_saat { get; set; }
        [DataType(DataType.Date)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:yyyy\\/MM\\/dd}")]
        public Nullable<System.DateTime> tarih { get; set; }
    
        public virtual personel personel { get; set; }
    }
}
