//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Personel_Finansal_Takip.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class is_giris_cikis
    {
        public int Id { get; set; }
        public Nullable<int> tur_id { get; set; }
        public Nullable<int> personel_id { get; set; }
        public Nullable<System.DateTime> tarihsaat { get; set; }
        public byte[] dogrulama_resmi { get; set; }
    
        public virtual is_giris_cikis_tur is_giris_cikis_tur { get; set; }
        public virtual personel personel { get; set; }
    }
}
