//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Personel_Finansal_Takip.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class izinler
    {
        public int id { get; set; }
        public Nullable<int> personel_id { get; set; }
        public Nullable<System.DateTime> talep_tarihi { get; set; }
        public Nullable<System.DateTime> onay_tarihi { get; set; }
        public Nullable<System.DateTime> son_degisiklik { get; set; }
        public Nullable<int> tur_id { get; set; }
        [DataType(DataType.Date)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:yyyy\\/MM\\/dd}")]
        public Nullable<System.DateTime> izin_baslangic { get; set; }
        [DataType(DataType.Date)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:yyyy\\/MM\\/dd}")]
        public Nullable<System.DateTime> izin_bitis { get; set; }
        [DataType(DataType.Date)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:yyyy\\/MM\\/dd}")]
        public Nullable<System.DateTime> ise_baslangic { get; set; }
        public Nullable<int> sure { get; set; }
        public Nullable<int> yol_izni { get; set; }
        public string izinde_bul_adres { get; set; }
        public string aciklama { get; set; }
        public Nullable<bool> red_durumu { get; set; }
    
        public virtual izin_tur izin_tur { get; set; }
        public virtual personel personel { get; set; }
    }
}
