//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Personel_Finansal_Takip.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class personeltakipsistemiEntities : DbContext
    {
        public personeltakipsistemiEntities()
            : base("name=personeltakipsistemiEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<fazla_mesai> fazla_mesai { get; set; }
        public virtual DbSet<gunler> gunlers { get; set; }
        public virtual DbSet<is_giris_cikis> is_giris_cikis { get; set; }
        public virtual DbSet<is_giris_cikis_tur> is_giris_cikis_tur { get; set; }
        public virtual DbSet<izin_tur> izin_tur { get; set; }
        public virtual DbSet<izinler> izinlers { get; set; }
        public virtual DbSet<maas> maas { get; set; }
        public virtual DbSet<oranlarbordro> oranlarbordroes { get; set; }
        public virtual DbSet<personel> personels { get; set; }
        public virtual DbSet<personel_puantaj> personel_puantaj { get; set; }
        public virtual DbSet<personel_rol> personel_rol { get; set; }
        public virtual DbSet<puantaj_gunler> puantaj_gunler { get; set; }
        public virtual DbSet<resmi_tatil> resmi_tatil { get; set; }
        public virtual DbSet<resmi_tatil_tur> resmi_tatil_tur { get; set; }
        public virtual DbSet<yillik_maas_raporlari> yillik_maas_raporlari { get; set; }
    }
}
