//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Personel_Finansal_Takip.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class oranlarbordro
    {
        public int Id { get; set; }
        public Nullable<double> sgk_primi_isci_payi { get; set; }
        public Nullable<double> issizlik_sigortasi_isci_payi { get; set; }
        public Nullable<double> kumulatif_gelir_vergisi_dilim_1 { get; set; }
        public Nullable<double> kumulatif_gelir_vergisi_dilim_2 { get; set; }
        public Nullable<double> kumulatif_gelir_vergisi_dilim_3 { get; set; }
        public Nullable<double> kumulatif_gelir_vergisi_dilim_4 { get; set; }
        public Nullable<double> damga_vergisi { get; set; }
        public Nullable<double> agi_kendisi { get; set; }
        public Nullable<double> agi_esi { get; set; }
        public Nullable<double> agi_cocuk_1 { get; set; }
        public Nullable<double> agi_cocuk_2 { get; set; }
        public Nullable<double> agi_cocuk_3 { get; set; }
        public Nullable<double> agi_cocuk_diger { get; set; }
        public Nullable<double> isveren_sgk_istisnasi { get; set; }
        public Nullable<double> issizlik_sigortasi_isveren_payi { get; set; }
        public Nullable<double> sgk_primi_isveren_payi { get; set; }
        public Nullable<double> sgk_primi_toplam { get; set; }
    }
}
