//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Personel_Finansal_Takip.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class personel_puantaj
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public personel_puantaj()
        {
            this.puantaj_gunler = new HashSet<puantaj_gunler>();
        }
    
        public int Id { get; set; }
        public Nullable<int> personel_id { get; set; }
        [DataType(DataType.Date)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:MMMM\\/yyyy}")]
        public Nullable<System.DateTime> ay_yil { get; set; }
        [DataType(DataType.Currency)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:0.##}")]
        public Nullable<double> brut_ucret { get; set; }
        [DataType(DataType.Currency)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:0.##}")]
        public Nullable<double> net_ucret { get; set; }
        public Nullable<double> calisilan_gun { get; set; }
        public Nullable<double> hafta_tatili { get; set; }
        public Nullable<double> genel_tatil { get; set; }
        public Nullable<double> ucretli_izin { get; set; }
        public Nullable<double> ucretsiz_izin { get; set; }
        public Nullable<double> sihhi_izin { get; set; }
        public Nullable<double> yillik_izin { get; set; }
        public Nullable<double> mazeretsiz_izin { get; set; }
        public Nullable<double> ucret_gun { get; set; }
        public Nullable<double> sigorta_gun { get; set; }
        public Nullable<double> sigorta_saat { get; set; }
        public Nullable<double> fazla_mesai_saat { get; set; }
    
        public virtual personel personel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<puantaj_gunler> puantaj_gunler { get; set; }
    }
}
