//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Personel_Finansal_Takip.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class personel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public personel()
        {
            this.fazla_mesai = new HashSet<fazla_mesai>();
            this.is_giris_cikis = new HashSet<is_giris_cikis>();
            this.izinlers = new HashSet<izinler>();
            this.maas = new HashSet<maas>();
            this.personel_puantaj = new HashSet<personel_puantaj>();
            this.yillik_maas_raporlari = new HashSet<yillik_maas_raporlari>();
        }
    
        public int id { get; set; }
        public string ad { get; set; }
        public string soyad { get; set; }
        public string ilk_soyad { get; set; }
        public string tc_kimlik_no { get; set; }
        public string cinsiyet { get; set; }
        [DataType(DataType.Date)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd\\/MMMM\\/yyyy}")]
        public Nullable<System.DateTime> dogum_tarihi { get; set; }
        public string dogum_yeri { get; set; }
        public string baba_adi { get; set; }
        public string anne_adi { get; set; }
        [DataType(DataType.Date)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd\\/MM\\/yyyy}")]
        public Nullable<System.DateTime> ise_giris_tarihi { get; set; }
        [DataType(DataType.Date)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd\\/MM\\/yyyy}")]
        public Nullable<System.DateTime> isten_cikis_tarihi { get; set; }
        public string ssk_no { get; set; }
        public string statu { get; set; }
        public string medeni_hal { get; set; }
        public Nullable<int> cocuk_sayisi { get; set; }
        public string departman { get; set; }
        public string gorev { get; set; }
        public string tahsil { get; set; }
        public string meslek { get; set; }
        public string ev_tel { get; set; }
        public string is_tel { get; set; }
        public string cep_tel { get; set; }
        public string e_posta { get; set; }
        public string sifre { get; set; }
        public Nullable<int> rol_id { get; set; }
        public string adres { get; set; }
        public string adres_il { get; set; }
        public string adres_ilce { get; set; }
        public string kan_grubu { get; set; }
        public string nufus_seri_no { get; set; }
        public string nufus_no { get; set; }
        public string nfs_kayitli_il { get; set; }
        public string nfs_kayitli_ilce { get; set; }
        public string nfs_kytli_mah_koy { get; set; }
        public Nullable<int> cilt_no { get; set; }
        public Nullable<int> aile_sira_no { get; set; }
        public Nullable<int> sira_no { get; set; }
        public Nullable<int> vergi_no { get; set; }
        public Nullable<int> haftalik_izin_gun { get; set; }
        public string aciklama { get; set; }
        public Nullable<int> ResimBoyutu { get; set; }
        public string DosyaIsmi { get; set; }
        public byte[] ResimVeri { get; set; }
        public Nullable<double> brut_maas { get; set; }
        public Nullable<double> net_maas { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<fazla_mesai> fazla_mesai { get; set; }
        public virtual gunler gunler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<is_giris_cikis> is_giris_cikis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<izinler> izinlers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<maas> maas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<personel_puantaj> personel_puantaj { get; set; }
        public virtual personel_rol personel_rol { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<yillik_maas_raporlari> yillik_maas_raporlari { get; set; }
    }
}
