//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Personel_Finansal_Takip.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class puantaj_gunler
    {
        public int Id { get; set; }
        public Nullable<int> personel_puantaj_id { get; set; }
        public Nullable<int> gun { get; set; }
        public string gun_pauntaj { get; set; }
    
        public virtual personel_puantaj personel_puantaj { get; set; }
    }
}
