//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Personel_Finansal_Takip.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class resmi_tatil
    {
        public int Id { get; set; }
        public Nullable<int> tur_id { get; set; }
        public Nullable<System.DateTime> tarih { get; set; }
    
        public virtual resmi_tatil_tur resmi_tatil_tur { get; set; }
    }
}
